force-app/main/default/objects/Custom_Object1__c/Custom_Object1__c.object-meta.xml
<CustomObject>
    <label>Custom Object1</label>
    <nameField>
        <label>Custom Object1 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Object1s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Object2__c/Custom_Object2__c.object-meta.xml
<CustomObject>
    <label>Custom Object2</label>
    <nameField>
        <label>Custom Object1 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Object2s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Object2__c/fields/Custom_Object1__c.field-meta.xml
<CustomField>
    <fullName>Custom_Object1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Custom Object1</label>
    <referenceTo>Custom_Object1__c</referenceTo>
    <relationshipLabel>Custom Object2s</relationshipLabel>
    <relationshipName>Custom_Object2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CutomObject1TriggerHandler.cls
public class CutomObject1TriggerHandler {

    public static void updateContactOwner(List<Custom_Object1__c> newAccounts, Map<Id, Custom_Object1__c> oldAccMap){

        Set<Id> accIds = new Set<Id>();
        Map<Id, Id> accIdMap = new Map<Id, Id>();
        List<Custom_Object2__c> conListUpdate = new List<Custom_Object2__c>();

        if(!newAccounts.isEmpty()){
            for(Custom_Object1__c newAccount : newAccounts){
                Custom_Object1__c oldAccount = oldAccMap.get(newAccount.Id);
                if(oldAccount.OwnerId != newAccount.OwnerId){
                    accIdMap.put(newAccount.Id, newAccount.OwnerId);
                    accIds.add(newAccount.Id);
                }
            }
        }

        List<Custom_Object2__c> cons = [SELECT Id, Custom_Object1__c, OwnerId FROM Custom_Object2__c WHERE Custom_Object1__c IN :accIds];

        for(Custom_Object2__c con : cons){
            if(accIdMap.containsKey(con.Custom_Object1__c)){
                con.OwnerId = accIdMap.get(con.Custom_Object1__c);
                conListUpdate.add(con);
            }
        }

        if(!conListUpdate.isEmpty()){
            update conListUpdate;
        }

    }

}